config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :posts do 
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end  

  resources :relationships
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :posts
  resources :users, only: [:show, :destroy, :update] do
    resources :items, only: [:create, :show, :destroy]
  end


  #Define the root URL
  root 'pages#index'

  #Definición de las rutas de las pages
  get '/home' => 'pages#home'

  get '/user/:id' => 'pages#profile'

  get '/explore' => 'pages#explore'

  delete '/user/:id' => 'users#destroy'

  patch '/user/:id' => 'users#update'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/explore.html.erb
<div class="row">
    <div class="col-xs-3">
        
        <div class="panel panel-default">
          <div class="panel-body">
            <h5 style="color: grey; font-size: 125%;">Explore</h5>
            <p style="opacity: 0.5; font-size: 90%;">

              <% if current_user.has_role? :admin %>
                  Warning,you are on Admin mode!! <br><br>
              <% end %>
              This page aggregates posts from ALL users. This means that you can find new people to follow,
              and your posts will also appear here so other people can see your opinions and interests and follow you
              if they chose.
            </p>
          </div>
        </div>
        
    </div>
    <div class="col-xs-6"><br>      
        <% for @p in @posts %>
        <div class="panel panel-default post-panel">
          <div class="panel-body row">
            
            <div class="col-sm-1">
                <p class="round-image-thumb"><%= image_tag(@p.user.avatar.url(:thumb)) %></p>
            </div>
            <div class="col-sm-11">
              <p class="post-title"><span class="post-owner"><a href="/user/<%= User.find(@p.user_id).username %>"><%= User.find(@p.user_id).username %></a></span> <span class="post-creation">- <%= @p.created_at.to_formatted_s(:short) %></span></p>
              <p class="post-content"><%= @p.content %></p>
              <p class="post-content"> <%= image_tag(@p.image.url(:medium))%> </p>

            </div>
            
            <div class="col-sm-12">
              <p class="post-links">
                
                <% if current_user.has_role? :admin %>
                  <%= link_to 'Delete', @p, method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>

                <%= link_to like_post_path(@p), method: :put do %>
                  <%= @p.get_upvotes.size %>
                  Like
                  <% if @p.get_upvotes.size >0%>
                    <span class="glyphicon glyphicon-heart g-links" aria-hidden="true"></span>
                  <%else%>
                    <span class="glyphicon glyphicon-heart-empty g-links" aria-hidden="true"></span>
                  <%end%>
                <% end %>

                <%= link_to dislike_post_path(@p), method: :put do %>
                  <%= @p.get_downvotes.size %>
                  Dislike
                <% end %>
                <span class="glyphicon glyphicon-retweet g-links" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-option-horizontal g-links" aria-hidden="true"></span>
              </p>
            </div>
            
          </div>
        </div>
        <% end %>
        
        <div class="panel panel-default post-panel">
          <div class="panel-body row">
            <div class="col-sm-12">
            <center><img src="/icon.png" height="25px" width="25px"></img>
              <a href="#top"><p class="opacity: .7;">Back to top <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span></p></a></center>
            </div>
          </div>
        </div>
    </div>
    <div class="col-xs-3">
        <div class="panel panel-default">
          <div class="panel-body">
             <h5 style="color: grey; font-size: 125%;">Who to follow</h5>
             <% for @u in @toFollow do %>
               <p style="font-weight: bold; opacity: 0.85;" ><a href="/user/<%= @u.username %>"><%= @u.username %></a></p>
               
             <% end %>
          </div>
        </div>
        
        <div class="panel panel-default">
          <div class="panel-body">
            <p style="opacity: 0.5; font-size: 90%;">© 2017 Railsfy About  Help  Terms  Privacy  Cookies  Ads Info  Brand  Blog  Status  Apps  Jobs  Advertise  Businesses  Media  Developers</p>
          </div>
        </div>
        
        
    </div>
</div>

app/views/pages/home.html.erb
<div class="row">
    <div class="col-xs-3">
       <div class="panel panel-default">
            <div class="panel-body">
                <p>Your feed</p>
                <div class="col-sm-6" style="font-size: 80%; opacity: 0.7;">POSTS<br>
                    <h6 style="color: #0084B4; font-size: 200%;"><%= current_user.posts.count %></h6>
                  </div>
                  <div class="col-sm-6" style="font-size: 80%; opacity: 0.7;">FOLLOWERS<br>
                    <h6 style="color: #0084B4; font-size: 200%;"><%= current_user.followers.count %></h6>
                  </div>
            </div>
        </div>
        
    </div>
    <div class="col-xs-6">
        <%= render  '/components/post_form' %><br><br>
        <% for @p in @posts %>
        <div class="panel panel-default post-panel">
            <div class="panel-body row">
                <div class="col-sm-1">
                    <p class="round-image-thumb"><%= image_tag(@p.user.avatar.url(:thumb)) %></p>


                </div>
                <div class="col-sm-11">
                    <p class="post-title"><span class="post-owner"><a href="/user/<%= User.find(@p.user_id).username %>"><%= User.find(@p.user_id).username %></a></span> <span class="post-creation">- <%= @p.created_at.to_formatted_s(:short) %></span></p>
                    <p class="post-content"> <%= @p.content %> </p>
                    <p class="post-content"> <%= image_tag(@p.image.url(:medium))%> </p>


                </div>

                <div class="col-sm-12">
                    <p class="post-links">
                
                        <%= link_to like_post_path(@p), method: :put do %>
                            <%= @p.get_upvotes.size %>
                            Like
                            <% if @p.get_upvotes.size >0%>
                            <span class="glyphicon glyphicon-heart g-links" aria-hidden="true"></span>
                            <%else%>
                            <span class="glyphicon glyphicon-heart-empty g-links" aria-hidden="true"></span>
                            <%end%>
                        <% end %>

                        <%= link_to dislike_post_path(@p), method: :put do %>
                            <%= @p.get_downvotes.size %>
                            Dislike
                        <% end %>
                        <span class="glyphicon glyphicon-retweet g-links" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-option-horizontal g-links" aria-hidden="true"></span>
                    </p>
                </div>
                
            </div>
        </div>
        <%end%>
    </div>
    <div class="col-xs-3">
        <div class="panel panel-default">
          <div class="panel-body">
             <h5 style="color: grey; font-size: 125%;">Who to follow</h5>
             <% for @u in @toFollow do %>
               <p style="font-weight: bold; opacity: 0.85;" ><a href="/user/<%= @u.username %>"><%= @u.username %></a></p>
             <% end %>
          </div>
        </div>
    </div>

app/views/pages/index.html.erb
<% if !user_signed_in? #if the user is not signed in ,we will render this %> 
    <style>
        body{
            background: url("/landscape.jpg") no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
        .container-index
    </style>

    <div class="container">
        <div class="jumbotron">
            <h1>Hi, friend!</h1>
            <p>Railsfy helps you to communicate with your friends!</p>
            <p><a class="btn btn-default btn-lg" href="/users/sign_in" role="button">Sign In</a></p>
            <p><a class="btn btn-default btn-lg" href="/users/sign_up" role="button">Sign Up</a></p>
            

        </div>
    </div>
<% else%>
    <script> document.location="/home"</script>
<%end%>

app/views/pages/profile.html.erb
<div class="row">
    <div class="col-xs-12">
        
    <div class="col-xs-3">

       <div class="panel panel-default">
            <div class="panel-body">
                <p>Profile of <%= @username%></p>
               
                <p class="round-image-50"><%= image_tag(User.find_by_username(@username).avatar.url(:thumb)) %></p>

                <div class="form-group">   
                </div>
            </div>
        </div>
    </div>

    <div class="col-xs-6">
      <%= render '/components/post_form' %>
        <br><br>
        <% for @p in @posts %>
        <div class="panel panel-default post-panel">
            <div class="panel-body row">
                <div class="col-sm-1">
                    <p class="round-image-thumb"><%= image_tag(@p.user.avatar.url(:thumb)) %></p>


                </div>
                <div class="col-sm-11">
                    <p class="post-title"><span class="post-owner"><a href="/user/<%= User.find(@p.user_id).username %>"><%= User.find(@p.user_id).username %></a></span> <span class="post-creation">- <%= @p.created_at.to_formatted_s(:short) %></span></p>
                    <p class="post-content"> <%= @p.content %> </p>
                    <p class="post-content"> <%= image_tag(@p.image.url(:medium))%> </p>
                        
                </div>

                <div class="col-sm-12">
                    <p class="post-links">
                        <%= link_to like_post_path(@p), method: :put do %>
                            <%= @p.get_upvotes.size %>
                                Like
                            <% if @p.get_upvotes.size >0%>
                                <span class="glyphicon glyphicon-heart g-links" aria-hidden="true"></span>
                            <%else%>
                                <span class="glyphicon glyphicon-heart-empty g-links" aria-hidden="true"></span>
                            <%end%>
                        <% end %>

                        <%= link_to dislike_post_path(@p), method: :put do %>
                            <%= @p.get_downvotes.size %>
                            Dislike
                        <% end %>
                        <td><%= link_to 'Delete', @p, method: :delete, data: { confirm: 'Are you sure?' } %></td>

                    </p>
                </div>
                
            </div>
        </div>
        <%end%>

    </div>

    <div class="col-xs-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <p> Who to Follow </p>
                <% for @u in @toFollow do %>
                    <p style="font-weight: bold; opacity: 0.85;" ><a href="/user/<%= @u.username %>"><%= @u.username %></a></p>
                <% end %>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <%= render '/components/follow_button',:user => User.find_by_username(params[:id]) %>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <% if current_user.has_role? :admin %>
                    <%= link_to 'Delete', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <img alt="Brand" src="/dialog_warning.png">

                <% end %>
                
            </div>
        </div>
        
    
    </div>
</div>
<!-- We start now with second row> -->
<!--<div class="row">
    <div class="col-xs-3 col-xs-offset-9">
        <div class="panel panel-default">
            <div class="panel-body">
                <p>About</p>
            </div>
        </div>
    </div>

    
</div>-->